language: php
php:
  - 5.5
  - 5.4
  - hhvm
  - 5.6
deploy:
  provider: travis
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  skip_cleanup: true
